---
kind: pipeline
type: docker
name: kishor-workshop

platform:
  arch: amd64
  os: linux

steps:
- name: auditt
  image: node:12-alpine
  commands:
  - yarn audit --verbose
  
---
kind: pipeline
type: docker
name: kishor-workshop-notification

platform:
  arch: amd64
  os: linux

steps:
- name: notify
  image: curlimages/curl:7.66.0
  commands:
  - "curl -X POST -H \"Content-Type: application/json\" -d '{\"@context\":\"https://schema.org/extensions\",\"@type\":\"MessageCard\",\"themeColor\":\"0072C6\",\"title\":\"Failed: ${DRONE_REPO_NAME}/${DRONE_COMMIT_BRANCH}    ...${DRONE_COMMIT_AUTHOR}\",\"text\":\"Commit [${DRONE_COMMIT_SHA} : ${DRONE_COMMIT_MESSAGE}]\n Steps failed: ${DRONE_FAILED_STAGES}\",\"potentialAction\":[{\"@type\":\"OpenUri\",\"name\":\"Check logs\",\"targets\":[{\"os\":\"default\",\"uri\":\"https://drone.daznplatform.com/${DRONE_REPO}/${DRONE_BUILD_NUMBER}\"}]}]}' https://outlook.office.com/webhook/7f871c30-4338-45b0-b65e-ac59e5bfade1@30459df5-1e53-4d8b-a162-0ad2348546f1/IncomingWebhook/3d12f00bfe294d2691b1b9483942dbc3/0aef5deb-1b0b-41f4-81e8-6d725c58242e"
trigger:
  status:
  - failure
